### ISSUE TITLE
Get a SAS token for access to secure storage

### ISSUE THREAD

**Issue by bigTimeBrad** [MerryFairyTalesAD440/API#13]

**Comment by mviencek** [comment]
Create a SAS token generator.  Attach to my personal account.  Test access for GET, PUT, and DELETE.  

Right now, it allows anonymous access.  Each token is good for only 30 minutes.  The response object is "message" and "uriandtoken" .  Message contains info about the uriandtoken array.  In order to get a response you need to pass a post to https://demofunctionsmikal-1-10-2019.azurewebsites.net/api/GetSAS

Generator can be tested here 

http://www.apirequest.io/5c4b26245957c90001748ca4?at=eyJhcHAiOiI1YzRiMjYyNDU5NTdjOTAwMDE3NDhjYTQiLCJhdWQiOiI2dVowbk9qZnJyOE5JajRyOEk2Tk51clN2RjdWWTJtTCIsInZlciI6IjEiLCJvcmciOiIwOjAiLCJwZXJtaXNzaW9ucyI6eyIwOjAiOnsic2NwIjoiY3JlYXRlOndvcmtzcGFjZXMgcmVhZDp3b3Jrc3BhY2VzIHVwZGF0ZTp3b3Jrc3BhY2VzIGRlbGV0ZTp3b3Jrc3BhY2VzIn19LCJleHAiOjE1NTA5NjY0MDAsImp0aSI6IjZmYjU1MjBjLTM4OTAtNDAzOC1iOTQ1LTJhZTE4YTliMzU2MyJ9.1GZsSlxbfzW3pTtTNKyfzbLEykXw1OiWFW34jrHtIfc

Waiting on info from devops to hook up to development (container url)

**Comment by mviencek** [comment]
Received necessary info from dev ops.  Create resources under class account.  Deploy getSAS function to class account.  Write console application to test upload.  Test function by uploading a text file and an image to container.  Tests successful.

Total time - 6 hours 

Function url - 
https://merryfairytales.azurewebsites.net/api/getSAS

To get token post "container": "getsastoken" in the body.  Response will be uri, token, and message.

**Comment by mviencek** [comment]
We can also test here - 

http://www.apirequest.io/5c4b26245957c90001748ca4?at=eyJhcHAiOiI1YzRiMjYyNDU5NTdjOTAwMDE3NDhjYTQiLCJhdWQiOiI2dVowbk9qZnJyOE5JajRyOEk2Tk51clN2RjdWWTJtTCIsInZlciI6IjEiLCJvcmciOiIwOjAiLCJwZXJtaXNzaW9ucyI6eyIwOjAiOnsic2NwIjoiY3JlYXRlOndvcmtzcGFjZXMgcmVhZDp3b3Jrc3BhY2VzIHVwZGF0ZTp3b3Jrc3BhY2VzIGRlbGV0ZTp3b3Jrc3BhY2VzIn19LCJleHAiOjE1NTA5NjY0MDAsImp0aSI6IjZmYjU1MjBjLTM4OTAtNDAzOC1iOTQ1LTJhZTE4YTliMzU2MyJ9.1GZsSlxbfzW3pTtTNKyfzbLEykXw1OiWFW34jrHtIfc

**Comment by mviencek** [comment]
Create Key Vault in Azure.  Revise project to include Key Vault, test locally, deploy and test deployment.  Additional time 1 hr

**Comment by mviencek** [comment]
Wiki page - 
https://github.com/MerryFairyTalesAD440/API/wiki/Get-SAS-Tokens

**Comment by mviencek** [comment]
function url -

https://merryfairytales.azurewebsites.net/api/getSAS

**Comment by mviencek** [comment]
Pull request -

https://github.com/MerryFairyTalesAD440/API/pull/19

**Comment by mviencek** [comment]
Window curl command - 
curl -X POST -d "{'container':'getsastoken'}" -v -i "https://merryfairytales.azurewebsites.net/v1/sastoken"

Linux curl command -
curl -X POST -d '{"container":"getsastoken"}' -v -i 'https://merryfairytales.azurewebsites.net/v1/sastoken'
